name: 2Download right now

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: 'Download Url'
        required: false
        default: 'false'
#   watch:
#     types: started
env:
  FILE_PATH: 'downloads'
  
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Aria2 Install
      run: sudo apt install -y aria2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        pip install install lk21==1.5.61 pymongo pymongo[srv] pymongo[tls] certifi

    - name: Downloading
      id: downloading
      run: |
        python download.py  --con="${{ secrets.DB_CONNECT }}" --isnow="1"
        filename=$(ls downloads | head -n1)
        echo "::set-output name=path::downloads/$filename"
        echo "::set-output name=filename::$filename"
        size=$(ls -l downloads/$filename | awk '{print $5}' )
        echo "::set-output name=size::$size"

    - uses: ykxVK8yL5L/add-to-web3@v1.5
      id: web3
      if: steps.downloading.outputs.filename != '' && !cancelled()
      with:
        web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
        path_to_add: "${{ steps.downloading.outputs.path }}"
        file_name: "${{ steps.downloading.outputs.filename }}"
        wrap_with_directory: true
   
    - name: Save Data
      id:  database
      if: steps.downloading.outputs.filename != '' && !cancelled()
      run: |
        python mongodb.py --con="${{ secrets.DB_CONNECT }}" --name="${{ steps.downloading.outputs.filename }}" --size="${{ steps.downloading.outputs.size }}" --cid="${{ steps.web3.outputs.cid }}"
        echo "::set-output name=status::ok"

    - name: Notify upload info to mqtt broker
      if: steps.database.outputs.status != '' && !cancelled()
      uses: juhrlass/mqtt-action@master
      with:
        protocol: mqtt
        host: broker-cn.emqx.io
        port: 1883
        topic: ${{ secrets.SYNC_TOPIC }}
        message: 'ok'
        username: ''
        password: ''

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}

# This part triggers the workflow to run again after it has completed
  rerun:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger Original Workflow
      uses: actions/github-script@v6
      with:
        script: |
          const { data: workflow } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.run_id }}
          });

          const { data: dispatch } = await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "repository_dispatch",
            client_payload: {
              rerun_workflow: true
            }
          });
          console.log(`Triggered original workflow: ${workflow.workflow.name}`);

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
