name: Rerun Original Workflow

on:
  workflow_run:
    workflows: ["download.yaml"]  # Replace with the name of your original workflow
    types:
      - completed

jobs:
  rerun:

    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Original Workflow
      uses: actions/github-script@v6
      with:
        script: |
          const { data: workflow } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.workflow_run.id }}
          });
          
          const { data: dispatch } = await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "repository_dispatch",
            client_payload: {
              rerun_workflow: true
            }
          });
          console.log(`Triggered original workflow: ${workflow.workflow.name}`);
          
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
