name: Rerun Original Workflow

on:
  workflow_run:
    workflows: ["2Download right now"] # Replace with the name of your original workflow
    types:
      - completed

jobs:
  rerun:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Add other steps for your original workflow here
    
    - name: Trigger Original Workflow
      uses: actions/github-script@v6
      with:
        script: |
          const { GitHub, context } = require('@actions/github'); // 导入模块
          const github = new GitHub(process.env.GITHUB_TOKEN); // 初始化 GitHub 对象

          const { data: workflow } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.run_id }}
          });

          const { data: dispatch } = await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "repository_dispatch",
            client_payload: {
              rerun_workflow: true
            }
          });
          console.log(`Triggered original workflow: ${workflow.workflow.name}`);

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
