name: Trigger Main Workflow

on:
  workflow_run:
    workflows: ["2Download right now"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Main Workflow
      uses: actions/github-script@v6
      with:
        script: |
          const { GitHub, context } = require('@actions/github');
          const github = new GitHub(process.env.GITHUB_TOKEN);

          const { data: dispatch } = await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "repository_dispatch",
            client_payload: {
              rerun_workflow: true
            }
          });
          console.log(`Triggered main workflow`);

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
